### PR TITLE
Add neoforge.mods.toml for modern neoforge

### LINKED ISSUE #4: My favorite mod (this one) won't load
image

### PR DESCRIPTION
**Pull request by dima-dencep**
Fixes #4

### CODE REVIEW

**Comment by dima-dencep** [comment]
I originally thought that your version 1.20.4 was not different from 1.20.6, but that doesn't seem to be the case

**Comment by Khajiitos** [comment]
I'm pretty sure 1.20.6 is a separate branch that I haven't pushed by accident. Maybe you could look into the JAR and figure out what's wrong?

**Comment by dima-dencep** [comment]
Note: cloth-config is not out for forge 1.20.6 (only fabric + neoforge)

**Comment by Khajiitos** [comment]
Hey, so I actually pushed all the changes that I forgot (1.20.4 is a separate branch, master is 1.20.6). Perhaps you could re-open the pull request considering all the changes I've already made, if it's not too inconvenient for you? Thanks a lot for your help :)

**Comment by dima-dencep** [comment]
done

**Comment by Khajiitos** [comment]
Thank you very much for the effort! And sorry for the delay :sweat:

**Pull request merged**
